modLoader = "javafml"
loaderVersion = "[0,)"
license="GPLv2.1"
issueTrackerURL = "https://github.com/matthewperiut/birdnests/issues"

[[mods]]
modId = "birdnest"
version = "${version}"
displayName = "Bird Nests!"
authors = "Daniking,Slainlight,DerpDerpling,Soumeh"
description = '''
Catching nests from trees can be rewarding...
'''
logoFile = "../icon.png"