modLoader="javafml" #mandatory
loaderVersion="[2,)" #mandatory
license="GPLv2.1"
issueTrackerURL = "https://github.com/matthewperiut/birdnests/issues"

[[mods]]
modId = "birdnest"
version = "${version}"
displayName = "Bird Nests!"
authors = "Daniking,Slainlight,DerpDerpling,Soumeh"
description = '''
Catching nests from trees can be rewarding...
'''
logoFile = "assets/birdnest/icon.png"

[[dependencies.birdnest]]
modId="minecraft"
type="required"
versionRange="[1.20.5,1.20.6]"

[[dependencies.birdnest]]
modId="neoforge"
type="required"
versionRange="[0,)"

[[dependencies.birdnest]]
modId="architectury"
type="required"
versionRange="[0,)"

[[dependencies.birdnest]]
modId="cryonicconfig"
type="required"
versionRange="[0,)"